[package]
name = "hematite_server"
version = "0.0.1"
authors = [
    "Fenhl <fenhl@fenhl.net>",
    "Carlos Cobo <toqueteos@gmail.com>"
]

[[bin]]
name = "hematite_server"
path = "server/main.rs"
doc = false
test = false
bench = false

[lib]
name = "hematite_server"
path = "src/lib.rs"

[dependencies]
byteorder = "*"
flate2 = "*"
num = "*"
regex = "*"
rustc-serialize = "*"
time = "*"
uuid = "*"

[dependencies.nbt]
git = "https://github.com/PistonDevelopers/hematite_nbt.git"
